### ISSUE TITLE
SecurityException : missing ACTIVITY_RECOGNITION

### ISSUE THREAD

**Issue by bsr203** [adsamcik/Tracker-Android#169]
Hi.
I am new to Android, and was looking for examples on recognition API. I setup API keys, and build is successful. It crashes as soon as the main screen loads with the below trace.

the error is
```
     Caused by: com.google.android.gms.common.api.ApiException: 10: SecurityException: Activity detection usage requires the ACTIVITY_RECOGNITION permission
```

I even added 
`<uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />`

to the `app/src/main/AndroidManifest.xml`, but same result. 

my emulator is API level 29.

Any help appreciated.

 thanks for your work on this project and open sourcing it.

Cheers
bsr
```
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xc6acfae0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xc6acfae0: ver 3 0 (tinfo 0xdda3cde0)
E/RecyclerView: No layout manager attached; skipping layout
W/Gralloc3: mapper 3.x is not supported
D/: createUnique: call
    HostConnection::get() New Host Connection established 0xddaca250, tid 14105
D/: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglMakeCurrent: 0xc6acfae0: ver 3 0 (tinfo 0xdda3cde0)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
W/signalcollecto: Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
    Got a deoptimization request on un-deoptimizable method java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adsamcik.signalcollector, PID: 14035
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: com.google.android.gms.common.api.ApiException: 10: SecurityException: Activity detection usage requires the ACTIVITY_RECOGNITION permission
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
        at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
        at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
        at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
        at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
        at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.setFailedResult(com.google.android.gms:play-services-base@@17.1.0:29)
        at com.google.android.gms.common.api.internal.zad.zaa(com.google.android.gms:play-services-base@@17.1.0:13)
        at com.google.android.gms.common.api.internal.zad.zac(com.google.android.gms:play-services-base@@17.1.0:7)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:167)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.1.0:134)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabg(com.google.android.gms:play-services-base@@17.1.0:99)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zabe(com.google.android.gms:play-services-base@@17.1.0:40)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnected(com.google.android.gms:play-services-base@@17.1.0:19)
        at com.google.android.gms.common.internal.zaf.onConnected(com.google.android.gms:play-services-base@@17.1.0:2)
        at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source:24)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source:12)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source:11)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:49)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at com.google.android.gms.internal.common.zze.dispatchMessage(Unknown Source:8)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
I/Process: Sending signal. PID: 14035 SIG: 9
Disconnected from the target VM, address: 'localhost:8612', transport: 'socket'
```

**Comment by bsr203** [comment]
sorry. i was using an emulator without play services

**Comment by adsamcik** [comment]
> 
> 
> sorry. i was using an emulator without play services

I did a little digging and from what I can tell this has nothing to do with not having play services but rather some issue with the Android 10 (emulator?). Could you tell me please, which emulator caused you problems?

I had the same issue with Android 10 Google Play emulator, but no issues with Android 9 Google Play emulator. If Play Services were missing, this shouldn't happen. First missing play services in this case would be caught by condition and second it wouldn't know about permission, it probably would just say something along the lines of "Class not found" or "Play services are missing".

**Comment by bsr203** [comment]
Hi. I just tried on 2 emulator

Pixel 2 API 28 (Pie). Which is a production ROM with google pay services
Pixel XL API 29 (Q) Without play services

It crashes on Q with the same error, and works great on Pie

I too not sure why the permission check not failed.

Android studio and plugins are upto date.

Thanks for looking into this.

**Comment by adsamcik** [comment]
> 
> 
> Hi. I just tried on 2 emulator
> <img alt="Screen Shot 2019-09-22 at 11 01 02 PM" width="1377" src="https://user-images.githubusercontent.com/1966521/65399857-f3fb3f80-dd8c-11e9-8afd-b079f7323aab.png">
> 
> Pixel 2 API 28 (Pie). Which is a production ROM with google pay services
> Pixel XL API 29 (Q) Without play services
> 
> It crashes on Q with the same error, and works great on Pie
> 
> I too not sure why the permission check not failed.
> 
> Android studio and plugins are upto date.
> 
> Thanks for looking into this.
> 
> EDIT:
> I created another
> Pixel XL API 28 (Pie) Without play services
> It opens the app fine
> 
> So I agree that it has something to do with Android 10 emulator

ok I looked into it more and I think I get where the problem is. I will fix it later today. The issue is that since the app targets Android 10, it needs to request the activity permission at runtime (https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition). This also explains why the google sample application I tried worked fine, because it only targets Android 9 and thus does not need to request this permission. It makes things a bit more complicated, but I understand why this change was made.

Also this issue wouldn't normally crash the app in production, it crashed the app because it was thrown in debug mode. I made some improvements to make it clearer where exactly it crashed within the app.

I'll close this issue once the fix it uploaded, thanks for finding it.

**Comment by gwicks56** [comment]
I am having this same issue, when I target API 28 but compile for API 29, but on actual phones. If I target and compile for API 29 no issue, but when I target 28 I am explicitly asked to give the permission, if I check whether I have the permission is confirms I do, if I check in the phone settings whether I have the permission it shows I have it, but it fails when trying to:
```

Task<Void> task =
                ActivityRecognition.getClient(this)
                        .requestActivityTransitionUpdates(request, transitionPendingIntent);
```

With error:
```
com.google.android.gms.common.api.ApiException: 10: SecurityException: Activity detection usage requires the ACTIVITY_RECOGNITION permission
```

**Comment by adsamcik** [comment]
This issue is closed and it does not seem related to this application since this application targets API 29 and there is no reason to target lower APIs.

Side note: might be cause it compiles for 29, but targets 28, try setting both to the same value.
